name: Scheduled FitBot run

on:
  schedule:
    - cron: "57 5 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      # - name: Build docker image
      #   run: make docker/build
      - name: Run fitbot (OPEN BOX)
        run: docker run -e email=${{ secrets.EMAIL }} -e password=${{ secrets.PASSWORD }} -e booking-goals={'\"0\":{\"time\":\"1800_60\"\,\"name\":\"OPEN\ BOX\"}\,\"1\":{\"time\":\"1800_60\"\,\"name\":\"OPEN\ BOX\"},\"2\":{\"time\":\"1800_60\"\,\"name\":\"WOD\"},\"3\":{\"time\":\"1800_60\"\,\"name\":\"OPEN\ BOX\"},\"4\":{\"time\":\"1800_60\"\,\"name\":\"OPEN\ BOX\"},\"5\":{\"time\":\"1100_60\"\,\"name\":\"OPEN\ BOX\"}'} -e box-name=${{ secrets.BOX_NAME }} -e box-id=${{ secrets.BOX_ID }} -e days-in-advance=4 pablobuenaposada/fitbot
      - name: Run fitbot (WOD)
        run: docker run -e email=${{ secrets.EMAIL }} -e password=${{ secrets.PASSWORD }} -e booking-goals={'\"0\":{\"time\":\"1900_60\"\,\"name\":\"WOD\"}\,\"1\":{\"time\":\"1900_60\"\,\"name\":\"WOD\"},\"2\":{\"time\":\"1900_60\"\,\"name\":\"WOD\"},\"3\":{\"time\":\"1900_60\"\,\"name\":\"WOD\"},\"4\":{\"time\":\"1900_60\"\,\"name\":\"WOD\"},\"5\":{\"time\":\"1200_60\"\,\"name\":\"WOD\"}'} -e box-name=${{ secrets.BOX_NAME }} -e box-id=${{ secrets.BOX_ID }} -e days-in-advance=4 pablobuenaposada/fitbot
