name: Scheduled test FitBot run

on:
  schedule:
    - cron: "0 22 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      # - name: Build docker image
      #   run: make docker/build
      - name: Run fitbot
        run: docker run -e email=${{ secrets.EMAIL }} -e password=${{ secrets.PASSWORD }} -e booking-goals={'\"0\":{\"time\":\"1800_60\"\,\"name\":\"WOD\"}\,\"1\":{\"time\":\"1800_60\"\,\"name\":\"WOD\"},\"2\":{\"time\":\"1800_60\"\,\"name\":\"WOD\"},\"3\":{\"time\":\"1800_60\"\,\"name\":\"WOD\"},\"4\":{\"time\":\"0800_60\"\,\"name\":\"WOD\"},\"6\":{\"time\":\"1000_60\"\,\"name\":\"WOD\"}'} -e box-name=${{ secrets.BOX_NAME }} -e box-id=${{ secrets.BOX_ID }} -e days-in-advance=2 pablobuenaposada/fitbot
